### PR TITLE
Update pubspec.yaml

### PR DESCRIPTION
**Pull request by giorgio79**

### CODE REVIEW

**Review by bilalsammour — COMMENTED** [review]
FB

**Comment by mitesh77** [comment]
Running "flutter pub get" in project...                      
Because geoflutterfire >=3.0.1 depends on cloud_firestore ^2.3.0 and wamo_admin depends on cloud_firestore ^3.1.4, geoflutterfire >=3.0.1 is forbidden.
So, because project depends on geoflutterfire ^3.0.1, version solving failed.
pub get failed (1; So, because project depends on geoflutterfire ^3.0.1, version solving failed.)
exit code 1


@xmany  can you fix this as soon as this dependency is outdated?

**Comment by kkorgol** [comment]
Please update dependencies to latest versions

**Comment by mitesh77** [comment]
Screenshot 2021-12-09 at 3 50 26 PM


you can check this is the latest but not now we need the latest support for flutter v2.8

**Comment by kkorgol** [comment]
To clarify I mean update dependencies by dev team responsible for this plugin and release new version of this plugin with actual dependencies. Each of us has same problem as you @mitesh77. Hope now that's clear. Regards

**Comment by myxzlpltk** [comment]
Does this work just by changing the version? Didn't the method name change too? What about null safety?

**Pull request merged**
